on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest  
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - run: flutter pub get

      # Build APK for Android
      - run: flutter build apk --release

      # Build iOS without code signing
      - run: flutter build ios --no-codesign

      # Upload iOS App Bundle (.app)
      - name: Archive iOS Build
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r ios-app.zip Payload

      # Upload artifacts (APK & iOS build)
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*,ios-app.zip"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
